### ISSUE TITLE
Reflection data of generic jobs has not automatically initialized

### ISSUE THREAD

**Issue by wish-wish** [NagaChiang/entity-tween#1]
i am a ecs newer, i add the package to 2020.2.1f1c1, then got the errors, i don't know what to do , how to do .
(0,0): error error DC3002: Timespawn.EntityTween.Tweens.TweenDestroySystem`1/DestroyJob: generic jobs cannot have their reflection data auto-registered - you must use the assembly-level RegisterGenericJobType attribute to specify which instantiations you need

(0,0): error error DC3002: Timespawn.EntityTween.Tweens.TweenGenerateSystem`4/GenerateJob: generic jobs cannot have their reflection data auto-registered - you must use the assembly-level RegisterGenericJobType attribute to specify which instantiations you need

(0,0): error error DC3002: Timespawn.EntityTween.Tweens.TweenDestroySystem`1/DestroyJob: generic jobs cannot have their reflection data auto-registered - you must use the assembly-level RegisterGenericJobType attribute to specify which instantiations you need

(0,0): error error DC3002: Timespawn.EntityTween.Tweens.TweenGenerateSystem`4/GenerateJob: generic jobs cannot have their reflection data auto-registered - you must use the assembly-level RegisterGenericJobType attribute to specify which instantiations you need

**Comment by NagaChiang** [comment]
According to the [thread](https://forum.unity.com/threads/entities-0-14-registergenericjobtype-job-reflection-data-has-not-been-automatically-computed.951990/), it's a bug about reflection of generic jobs in Unity 2020.2.

Meanwhile, please use this package in Unity 2020.1. Thanks for the report!

**Comment by NagaChiang** [comment]
This issue has been fixed in v0.6.0 with dependency upgrade. Now it's compatible with 2020.3.
