### ISSUE TITLE
Coming back zero point after finish

### ISSUE THREAD

**Issue by xOrfe** [NagaChiang/entity-tween#2]
Thank you sooo much for this beatiful repo :p , entity coming back start point(immediately) after reach end point. I cant figure out why.

            Entities.
                WithAll<Block>().
                ForEach((Entity entity,in Translation translation) => {
                    float3 start = translation.Value;
                    float3 end = new float3(20.0f, 20.0f, 0);
                    float duration = 1.0f;
                    bool isPingPong = false;
                    int loopCount = 1;
                    
                    Tween.Move(ecb,0, entity, start, end, duration);
                }).Schedule();

**Comment by NagaChiang** [comment]
I think I've reproduced the bug. Let me find some time to fix it, thanks!

**Comment by NagaChiang** [comment]
This issue has been fixed in v0.5.1. Please update the package.

Thanks for the report, especially for such a really common case.
